CREATE TABLE IF NOT EXISTS history_item (
    id SERIAL PRIMARY KEY,
    user_id UUID NOT NULL,
    aid_id INT NOT NULL,
    quantity INT NOT NULL DEFAULT 1,
    price NUMERIC(10,2) NOT NULL,
    bought_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);